language: ruby
cache: bundler
bundler_args: --without documentation production
rvm:
  - 2.1.7
  - 2.2.3
  - jruby-19mode
  - rbx
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
script:
  - bundle exec rspec --tag ~type:integration
